# general configuration
url: "http://yokomeshi.github.io"
baseurl:

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/selfie.png"
  # author will appear under the avatar (optional)
  author: "Jon Lexa"
  # tagline will appear under the title (optional)
  tagline: "Technologist. Photographer. Explorer."
  # email
  email:  whisper@jonlexa.com
  # twitter username
  twitter_username:  jonlexa
  # linkedin username
  linkedin_username:  jonlexa
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# HTTPS enforcement
url: https://jonlexa.com
enforce_ssl: jonlexa.com

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
